### ISSUE TITLE
Does this project support for Unity WebGL build?

### ISSUE THREAD

**Issue by game-libgdx-unity** [FirebaseExtended/unity-solutions#16]
Does this project support for Unity WebGL build?

**Comment by dzlier-gcp** [comment]
Unfortunately, the Firebase Unity SDK (on which this asset is built) is only available for Android and iOS. While you can use Firebase's REST API to interact with the Database, this asset would have to be modified to use that instead of the .NET implementation, and you would separately have to solve the auth issue, which is that anyone can see the JSON (including auth info) being sent to and from the server in a web application.
